[[pages]]
path = "main.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/spotify_sync.py"
name = "Spotify Sync"
icon = "ğŸ§"

[[pages]]
path = "pages/saved_artists.py"
name = "Saved Artists"
icon = "ğŸ“‹"

[[pages]]
path = "pages/callback.py"
name = "Spotify Callback"
icon = "ğŸ§"
hidden = true
show_in_sidebar = false 